server:
  port: 8888
spring:
  application:
    name: projeto-spring-boot-user
  security:
    user:
      name: user
      password: user
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
api:
  security:
    token:
      secret: ${JWT_SECRET:secret}